spring:
  datasource:
    username: codelex
    password: codelex
    url: jdbc:postgresql://localhost:5432/security_app
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/liquibase/updates.xml
    enabled: true

maps:
  api-url: https://maps.googleapis.com/maps/api/distancematrix/json?units=metric&origins=
  api-key: AIzaSyDcsLDxrAteVZEOc4h8zBJwVzs13Cb79OU